highlighter: pygments
baseurl: /blog
default_page_title: 'Patrick Cockwell | An Uncommon Approach To Life'
markdown: redcarpet
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
